apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
  
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: django
        image: anjali16897/django:latest
        ports:
        - containerPort: 8000